import { useMemo, useState } from 'react';
import './recipe-gallery.css';
import recipesIndex from '../public/api/recipes.json';

/* ============================================================================
 * Phase 6 S.1 — recipe gallery faceted search.
 *
 * Reads the in-tree `docs/public/api/recipes.json` (regenerated by
 * `docs/scripts/generate-recipes-index.ts` from the layer directories +
 * `docs/data/recipe-facets.json` overlay per ADR-0024 §1+§2).
 *
 * v1 surface:
 *   - free-text substring search across slug/project/title/symptom/tags
 *   - facet chip groups for layer (1/2/3), language, severity
 *   - chips OR within group, AND across groups
 *   - 11 recipes today; client-side filter is faster than Pagefind for
 *     this scale (ADR-0024 §3)
 * ========================================================================== */

interface RecipeEntry {
  slug: string;
  layer: 1 | 2 | 3;
  project: string;
  issue: number;
  title: string;
  page_url: string;
  source_url: string;
  verdict_url?: string;
  language: string;
  symptom?: string;
  severity?: string;
  tags: string[];
}

interface RecipesIndex {
  index: 'v1';
  contract: 'v1';
  recipes: RecipeEntry[];
}

const INDEX = recipesIndex as RecipesIndex;

/* --------------------------------- i18n ---------------------------------- */

type Lang = 'en' | 'ja';

interface Strings {
  eyebrow: string;
  searchLabel: string;
  searchPlaceholder: string;
  layerLabel: string;
  languageLabel: string;
  severityLabel: string;
  resultsTemplate: (n: number, total: number) => string;
  emptyState: string;
  clearFilters: string;
  open: string;
  source: string;
  layerName: (layer: 1 | 2 | 3) => string;
  unknownLanguage: string;
}

const STRINGS: Record<Lang, Strings> = {
  en: {
    eyebrow: '// CATALOGUE · FACETED',
    searchLabel: 'Search',
    searchPlaceholder: 'project, slug, symptom, tag…',
    layerLabel: 'Layer',
    languageLabel: 'Language',
    severityLabel: 'Severity',
    resultsTemplate: (n, total) => `showing ${n} of ${total}`,
    emptyState: 'No recipes match these filters.',
    clearFilters: 'clear filters',
    open: 'Open ↗',
    source: 'Source',
    layerName: (layer) =>
      layer === 1
        ? 'L1 · WASM'
        : layer === 2
          ? 'L2 · Docker'
          : 'L3 · Record-replay',
    unknownLanguage: 'unknown',
  },
  ja: {
    eyebrow: '// カタログ · ファセット',
    searchLabel: '検索',
    searchPlaceholder: 'project、slug、symptom、タグ…',
    layerLabel: 'レイヤー',
    languageLabel: '言語',
    severityLabel: '深刻度',
    resultsTemplate: (n, total) => `${total} 件中 ${n} 件表示`,
    emptyState: 'このフィルタ条件に該当するレシピがない。',
    clearFilters: 'フィルタをクリア',
    open: '開く ↗',
    source: 'ソース',
    layerName: (layer) =>
      layer === 1 ? 'L1 · WASM' : layer === 2 ? 'L2 · Docker' : 'L3 · 記録再生',
    unknownLanguage: '未指定',
  },
};

/* ----------------------------- Helpers --------------------------------- */

// Rewrite the production-host URL baked into recipes.json so that, when
// served from a different origin (local rspress dev at localhost:3000,
// a fork's Pages deploy, an rspress preview), the "Open" link points
// at the gallery's own host instead of the upstream Pages site. The
// pathname (`/<base>/repro/<project>/<issue>/`) is preserved verbatim;
// only the origin is swapped. SSR is left untouched.
function localizeRecipeUrl(url: string): string {
  if (typeof window === 'undefined') return url;
  try {
    const u = new URL(url);
    return window.location.origin + u.pathname + u.search + u.hash;
  } catch {
    return url;
  }
}

function uniqueValues<T>(
  items: RecipeEntry[],
  pick: (r: RecipeEntry) => T | undefined,
): T[] {
  const seen = new Set<T>();
  for (const item of items) {
    const v = pick(item);
    if (v !== undefined) seen.add(v);
  }
  return Array.from(seen).sort();
}

function matchesQuery(recipe: RecipeEntry, query: string): boolean {
  if (!query) return true;
  const q = query.toLowerCase();
  if (recipe.slug.toLowerCase().includes(q)) return true;
  if (recipe.project.toLowerCase().includes(q)) return true;
  if (recipe.title.toLowerCase().includes(q)) return true;
  if (recipe.symptom?.toLowerCase().includes(q)) return true;
  for (const tag of recipe.tags) {
    if (tag.toLowerCase().includes(q)) return true;
  }
  return false;
}

/* ----------------------------- Components ------------------------------ */

function Chip({
  active,
  onToggle,
  children,
  accent,
}: {
  active: boolean;
  onToggle: () => void;
  children: React.ReactNode;
  accent?: 'teal' | 'violet' | 'coral' | 'neutral';
}) {
  const klass =
    'v-rg__chip' +
    (active ? ' v-rg__chip--on' : '') +
    (accent ? ` v-rg__chip--${accent}` : '');
  return (
    <button
      type="button"
      className={klass}
      onClick={onToggle}
      aria-pressed={active}
    >
      {children}
    </button>
  );
}

function FacetGroup({
  label,
  values,
  active,
  toggle,
  accent,
}: {
  label: string;
  values: string[];
  active: Set<string>;
  toggle: (v: string) => void;
  accent?: 'teal' | 'violet' | 'coral' | 'neutral';
}) {
  if (values.length === 0) return null;
  return (
    <div className="v-rg__group">
      <span className="v-rg__group-label">{label}</span>
      <div className="v-rg__chips">
        {values.map((v) => (
          <Chip
            key={v}
            active={active.has(v)}
            onToggle={() => toggle(v)}
            accent={accent}
          >
            {v}
          </Chip>
        ))}
      </div>
    </div>
  );
}

function RecipeCard({ lang, recipe }: { lang: Lang; recipe: RecipeEntry }) {
  const s = STRINGS[lang];
  const layerAccent =
    recipe.layer === 1 ? 'teal' : recipe.layer === 2 ? 'violet' : 'coral';
  return (
    <article className="v-rg__card">
      <header className="v-rg__card-head">
        <span className={`v-rg__layer-pill v-rg__layer-pill--${layerAccent}`}>
          {s.layerName(recipe.layer)}
        </span>
        <code className="v-rg__slug">{recipe.slug}</code>
      </header>
      <h3 className="v-rg__title">
        {recipe.project}
        {recipe.issue > 0 ? <span>#{recipe.issue}</span> : null}
      </h3>
      <p className="v-rg__lede">{recipe.title}</p>
      <div className="v-rg__meta">
        <span className="v-rg__meta-item">
          <span className="v-rg__meta-key">lang</span>{' '}
          <code>{recipe.language || s.unknownLanguage}</code>
        </span>
        {recipe.severity ? (
          <span className="v-rg__meta-item">
            <span className="v-rg__meta-key">severity</span>{' '}
            <code>{recipe.severity}</code>
          </span>
        ) : null}
        {recipe.symptom ? (
          <span className="v-rg__meta-item v-rg__meta-item--symptom">
            <span className="v-rg__meta-key">symptom</span>{' '}
            <code>{recipe.symptom}</code>
          </span>
        ) : null}
      </div>
      {recipe.tags.length > 0 ? (
        <div className="v-rg__tags">
          {recipe.tags.map((t) => (
            <span key={t} className="v-rg__tag">
              {t}
            </span>
          ))}
        </div>
      ) : null}
      <div className="v-rg__actions">
        <a
          className="v-rg__btn v-rg__btn--primary"
          href={localizeRecipeUrl(recipe.page_url)}
          target="_blank"
          rel="noreferrer"
        >
          {s.open}
        </a>
        <a
          className="v-rg__btn v-rg__btn--ghost"
          href={recipe.source_url}
          target="_blank"
          rel="noreferrer"
        >
          {s.source}
        </a>
      </div>
    </article>
  );
}

/* ------------------------------ Main app ------------------------------- */

export function RecipeGallery({ lang }: { lang: Lang }) {
  const s = STRINGS[lang];
  const all = INDEX.recipes;

  const [query, setQuery] = useState('');
  const [layers, setLayers] = useState<Set<number>>(new Set());
  const [languages, setLanguages] = useState<Set<string>>(new Set());
  const [severities, setSeverities] = useState<Set<string>>(new Set());

  const allLayers = useMemo<(1 | 2 | 3)[]>(
    () => uniqueValues(all, (r) => r.layer).map((n) => n as 1 | 2 | 3),
    [],
  );
  const allLanguages = useMemo(
    () => uniqueValues(all, (r) => r.language || undefined),
    [],
  );
  const allSeverities = useMemo(() => uniqueValues(all, (r) => r.severity), []);

  const toggleSet = <T,>(set: Set<T>, v: T): Set<T> => {
    const next = new Set(set);
    if (next.has(v)) next.delete(v);
    else next.add(v);
    return next;
  };

  const filtered = useMemo(() => {
    return all.filter((r) => {
      if (!matchesQuery(r, query)) return false;
      if (layers.size > 0 && !layers.has(r.layer)) return false;
      if (languages.size > 0 && !languages.has(r.language)) return false;
      if (severities.size > 0 && (!r.severity || !severities.has(r.severity)))
        return false;
      return true;
    });
  }, [query, layers, languages, severities]);

  const hasFilters =
    query.length > 0 ||
    layers.size > 0 ||
    languages.size > 0 ||
    severities.size > 0;

  const clearAll = () => {
    setQuery('');
    setLayers(new Set());
    setLanguages(new Set());
    setSeverities(new Set());
  };

  return (
    <section className="v-rg">
      <p className="v-rg__eyebrow">{s.eyebrow}</p>
      <div className="v-rg__controls">
        <label className="v-rg__search">
          <span className="v-rg__search-label">{s.searchLabel}</span>
          <input
            type="search"
            className="v-rg__search-input"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder={s.searchPlaceholder}
            spellCheck={false}
            autoCapitalize="off"
            autoCorrect="off"
          />
        </label>
        <FacetGroup
          label={s.layerLabel}
          values={allLayers.map(String)}
          active={new Set(Array.from(layers).map(String))}
          toggle={(v) => setLayers((prev) => toggleSet(prev, Number(v)))}
          accent="teal"
        />
        <FacetGroup
          label={s.languageLabel}
          values={allLanguages}
          active={languages}
          toggle={(v) => setLanguages((prev) => toggleSet(prev, v))}
          accent="violet"
        />
        <FacetGroup
          label={s.severityLabel}
          values={allSeverities}
          active={severities}
          toggle={(v) => setSeverities((prev) => toggleSet(prev, v))}
          accent="coral"
        />
      </div>
      <div className="v-rg__resultbar">
        <span className="v-rg__count">
          {s.resultsTemplate(filtered.length, all.length)}
        </span>
        {hasFilters ? (
          <button type="button" className="v-rg__clear" onClick={clearAll}>
            {s.clearFilters}
          </button>
        ) : null}
      </div>
      {filtered.length === 0 ? (
        <p className="v-rg__empty">{s.emptyState}</p>
      ) : (
        <div className="v-rg__cards">
          {filtered.map((recipe) => (
            <RecipeCard key={recipe.slug} lang={lang} recipe={recipe} />
          ))}
        </div>
      )}
    </section>
  );
}

export default RecipeGallery;
