version = "1"

php-version = "8.2"

[source]
paths = ["src/layer1_wasm/php-12167"]

[formatter]
print-width = 100

[linter.rules]
strict-types = { enabled = false }
no-isset = { enabled = false }
no-shorthand-ternary = { enabled = false }
no-else-clause = { enabled = false }
literal-named-argument = { enabled = false }
