toml-version = "v1.0.0"

[files]
include = ["**/*.toml"]
exclude = [
  "**/node_modules/**",
  "**/dist/**",
  "**/target/**",
  "**/doc_build/**",
  "**/.venv/**",
  ".sl/**",
]

[schema]
enabled = true
