import "../_assets/chrome.js";

const L2_STRINGS = {
  en: {
    fetching: "Fetching CI verdict snapshot\u2026",
    devNotice:
      "verdict snapshot is generated by CI; not available in local dev \u2014 see GitHub Pages for the live snapshot.",
    devOutput: "(verdict.json absent in dev preview)",
    devProgress: "Snapshot unavailable in dev.",
    complete: "Reproduction complete.",
    reproduced: "bug reproduced",
    unreproduced: "bug not reproduced",
    capturedAt: (headline, at) => `${headline} (CI snapshot captured ${at})`,
    image: (v) => `Image: ${v}`,
    digest: (v) => `Digest: ${v}`,
    exitCode: (v) => `Exit code: ${v}`,
    captured: (v) => `Captured at: ${v}`,
    noStdout: "(no stdout captured)",
    unavailable: (m) => `verdict snapshot unavailable: ${m}`,
    unknownError: "unknown error",
  },
  ja: {
    fetching: "CI \u306e verdict \u30b9\u30ca\u30c3\u30d7\u30b7\u30e7\u30c3\u30c8\u3092\u53d6\u5f97\u4e2d\u2026",
    devNotice:
      "verdict \u30b9\u30ca\u30c3\u30d7\u30b7\u30e7\u30c3\u30c8\u306f CI \u304c\u751f\u6210\u3059\u308b\u3002\u30ed\u30fc\u30ab\u30eb\u306e dev \u3067\u306f\u53c2\u7167\u3067\u304d\u306a\u3044 \u2014 \u30e9\u30a4\u30d6\u306e\u30b9\u30ca\u30c3\u30d7\u30b7\u30e7\u30c3\u30c8\u306f GitHub Pages \u3092\u898b\u308b\u3002",
    devOutput: "(dev \u30d7\u30ec\u30d3\u30e5\u30fc\u3067\u306f verdict.json \u306f\u5b58\u5728\u3057\u306a\u3044)",
    devProgress: "dev \u3067\u306f\u30b9\u30ca\u30c3\u30d7\u30b7\u30e7\u30c3\u30c8\u3092\u53c2\u7167\u3067\u304d\u306a\u3044\u3002",
    complete: "\u518d\u73fe\u5b8c\u4e86\u3002",
    reproduced: "bug \u3092\u518d\u73fe\u3057\u305f",
    unreproduced: "bug \u306f\u518d\u73fe\u3057\u306a\u304b\u3063\u305f",
    capturedAt: (headline, at) =>
      `${headline} (CI \u30b9\u30ca\u30c3\u30d7\u30b7\u30e7\u30c3\u30c8\u306e\u53d6\u5f97\u65e5\u6642: ${at})`,
    image: (v) => `\u30a4\u30e1\u30fc\u30b8: ${v}`,
    digest: (v) => `Digest: ${v}`,
    exitCode: (v) => `\u7d42\u4e86\u30b3\u30fc\u30c9: ${v}`,
    captured: (v) => `\u53d6\u5f97\u65e5\u6642: ${v}`,
    noStdout: "(stdout \u306f\u53d6\u5f97\u3055\u308c\u3066\u3044\u306a\u3044)",
    unavailable: (m) => `verdict \u30b9\u30ca\u30c3\u30d7\u30b7\u30e7\u30c3\u30c8\u3092\u53c2\u7167\u3067\u304d\u306a\u3044: ${m}`,
    unknownError: "\u4e0d\u660e\u306a\u30a8\u30e9\u30fc",
  },
};

const L2 =
  L2_STRINGS[document.documentElement.lang === "ja" ? "ja" : "en"];

export async function renderVerdictSnapshot(options) {
  const verdictUrl = options.verdictUrl ?? "./verdict.json";
  const bug = options.bug;

  const verdictEl = document.getElementById("verdict");
  const metaEl = document.getElementById("meta");
  const outputEl = document.getElementById("output");

  if (!verdictEl) {
    throw new Error('layer2: missing element with id="verdict".');
  }

  function setVerdict(state, text) {
    verdictEl.classList.remove("reproduced", "unreproduced", "pending");
    verdictEl.classList.add(state);
    verdictEl.dataset.verdict = state;
    verdictEl.textContent = text;
    globalThis.__VIVARIUM_VERDICT__ = state;

    if (state !== "pending") {
      document.dispatchEvent(
        new CustomEvent("vh-progress", {
          detail: { stage: "done", pct: 100, label: L2.complete },
        }),
      );
    }
  }

  setVerdict("pending", L2.fetching);

  try {
    const response = await fetch(verdictUrl, { cache: "no-cache" });
    if (!response.ok) {
      throw new Error(
        `failed to fetch ${verdictUrl}: HTTP ${response.status} ${response.statusText}`,
      );
    }
    const text = await response.text();
    let snap;
    try {
      snap = JSON.parse(text);
    } catch {
      setVerdict(
        "pending",
        L2.devNotice,
      );
      if (metaEl) metaEl.textContent = "";
      if (outputEl) outputEl.textContent = L2.devOutput;
      document.dispatchEvent(
        new CustomEvent("vh-progress", {
          detail: { stage: "done", pct: 100, label: L2.devProgress },
        }),
      );
      return;
    }

    if (snap.contract !== "v1") {
      throw new Error(
        `verdict.json contract mismatch: expected "v1", got ${JSON.stringify(snap.contract)}`,
      );
    }

    const verdict = snap.verdict;
    if (verdict !== "reproduced" && verdict !== "unreproduced") {
      throw new Error(
        `verdict.json verdict must be "reproduced" or "unreproduced"; got ${JSON.stringify(verdict)}`,
      );
    }

    const headline = verdict === "reproduced" ? L2.reproduced : L2.unreproduced;
    setVerdict(
      verdict,
      L2.capturedAt(headline, snap.captured_at),
    );

    if (metaEl) {
      const lines = [
        L2.image(snap.image_tag),
        snap.image_digest ? L2.digest(snap.image_digest) : null,
        L2.exitCode(snap.exit_code),
        L2.captured(snap.captured_at),
      ].filter(Boolean);
      metaEl.replaceChildren();
      lines.forEach((line, i) => {
        if (i > 0) metaEl.appendChild(document.createElement("br"));
        metaEl.appendChild(document.createTextNode(line));
      });
    }

    if (outputEl) {
      outputEl.textContent = snap.stdout || L2.noStdout;
    }

    globalThis.__VIVARIUM_RESULT__ = {
      contract: "v1",
      bug,
      runtime: {
        name: "docker-snapshot",
        version: snap.image_digest || snap.image_tag,
        extras: {
          image_tag: snap.image_tag,
          captured_at: snap.captured_at,
        },
      },
      result: {
        exit_code: snap.exit_code,
        verdict,
        stderr_tail: snap.stderr_tail || "",
      },
      timing: {
        started_at: snap.captured_at,
        finished_at: snap.captured_at,
        duration_ms: 0,
      },
    };
  } catch (err) {
    console.error(err);
    const msg = (err && (err.message || String(err))) || L2.unknownError;
    setVerdict("unreproduced", L2.unavailable(msg));
    if (outputEl) outputEl.textContent = String(err.stack || err.message || err);
  }
}
