// MCP tool that opens a draft PR on the upstream repository from the
// contributor's already-pushed fork branch. The output side of the
// round-trip loop — the first step that crosses the boundary from
// "internal verification" to "publicly visible state change".
//
// Phase 4 of the round-trip automation. Conservative by design:
//   - dry_run defaults to true; explicit opt-in needed to actually
//     create the PR.
//   - The PR is always opened with --draft. Merging out of draft
//     stays a human action.
//   - AI authorship is disclosed in the PR body (boilerplate footer
//     appended automatically). Label-based disclosure is NOT
//     attempted: AGENTS.md §4.6's `ai: generated` label is a
//     Vivarium-internal contract — the upstream repo may not have
//     that label and contributors typically lack write permission
//     to create it.
//   - The tool refuses to run unless the recipe's full round-trip
//     state machine selects `open_fork_pr` next — that is, the
//     status is not blocked/merged, an upstream PR is not already
//     open, the unfixed+fixed verdicts are both captured with the
//     expected polarity, and the Vivarium-side PR has already been
//     opened. Each of those conditions is enforced upstream by
//     `computeNextAction` so this tool stays consistent with it.
//   - Local clone, commit, and push are caller responsibilities —
//     this tool does NOT mutate the working tree. The fork branch
//     must already exist on GitHub before calling.

import { spawnSync } from 'node:child_process';

import { getCatalogue } from '../catalogue.js';
import type { RoundtripState } from '../types.js';
import {
  computeNextAction,
  parseUpstreamIssue,
} from './verify_and_report_fix.js';

export interface CreateForkPrArgs {
  slug: string;
  current_state: Partial<RoundtripState>;
  pr_title: string;
  pr_body?: string;
  dry_run?: boolean;
}

export interface CreateForkPrOk {
  ok: true;
  slug: string;
  upstream_repo: string;
  head: string;
  title: string;
  // The body actually submitted to gh — i.e. the caller-supplied
  // pr_body with the AI-authorship disclosure footer appended. Use
  // this rather than the raw input when reporting to the caller.
  body: string;
  draft: true;
  dry_run: boolean;
  command: string;
  pr_url?: string;
}

export interface CreateForkPrError {
  ok: false;
  error: string;
}

export type CreateForkPrResult = CreateForkPrOk | CreateForkPrError;

export interface GhRunResult {
  status: number | null;
  stdout: string;
  stderr: string;
}

export type GhRunner = (args: string[]) => GhRunResult;

const defaultGhRunner: GhRunner = (args) => {
  const r = spawnSync('gh', args, {
    encoding: 'utf-8',
    timeout: 60_000,
  });
  return {
    status: r.status,
    stdout: r.stdout ?? '',
    stderr: r.stderr ?? '',
  };
};

let ghRunner: GhRunner = defaultGhRunner;

export function _setGhRunnerForTesting(runner: GhRunner | null): void {
  ghRunner = runner ?? defaultGhRunner;
}

// Boilerplate appended to every upstream PR body so the AI authorship
// disclosure is visible to upstream maintainers. The `ai: generated`
// LABEL from AGENTS.md §4.6 is a Vivarium-internal contract; upstream
// repos may not carry that label, and contributors typically lack the
// write permission needed to create it. Disclose in prose instead.
const AI_AUTHORSHIP_FOOTER =
  '\n\n---\n\n*This pull request was generated by an AI agent via the Vivarium round-trip automation. The candidate fix was verified against an in-Vivarium reproduction (`verdicts.unfixed = "reproduced"` → `verdicts.fixed = "unreproduced"`). Please review carefully before merging.*\n';

function appendAuthorshipFooter(body: string): string {
  // Idempotent: a caller that already pasted the footer (or part of
  // it) shouldn't see it duplicated.
  if (body.includes('Vivarium round-trip automation')) return body;
  return body.length === 0
    ? AI_AUTHORSHIP_FOOTER.trimStart()
    : body + AI_AUTHORSHIP_FOOTER;
}

function quoteShell(value: string): string {
  // Single-quote and escape any embedded single quote — produces
  // a shell-safe representation for the returned `command` string.
  // Real execution goes through spawn with argv arrays, so this
  // affects only what the caller sees as a paste-ready line.
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

export async function createForkPr(
  args: CreateForkPrArgs,
): Promise<CreateForkPrResult> {
  const slug = args.slug?.trim();
  if (!slug) {
    return { ok: false, error: 'missing required argument: slug' };
  }

  const title = args.pr_title?.trim();
  if (!title) {
    return { ok: false, error: 'pr_title is required' };
  }

  const { recipes } = await getCatalogue();
  const recipe = recipes.find((r) => r.slug === slug);
  if (!recipe) {
    return { ok: false, error: `recipe not found: ${slug}` };
  }

  const state = args.current_state;
  if (!state || typeof state !== 'object') {
    return { ok: false, error: 'current_state is required' };
  }

  // State-machine integrity: the upstream PR is only the next legal
  // action when `computeNextAction(state) === 'open_fork_pr'`. That
  // single check enforces all the round-trip preconditions in one
  // place — `status` is not blocked/merged, an upstream_pr is not
  // already recorded, the verdicts are both captured with the
  // expected polarity (unfixed=reproduced + fixed=unreproduced),
  // and a Vivarium-side `vivarium_pr` has already been opened.
  // Using the same function the rest of the tooling uses avoids
  // drift between this tool and `verify_and_report_fix`.
  const nextAction = computeNextAction(state);
  if (nextAction !== 'open_fork_pr') {
    return {
      ok: false,
      error: `state machine expected next_action 'open_fork_pr' but computeNextAction(current_state) returned '${nextAction}'. Resolve the round-trip state first (capture verdicts, open the Vivarium-side PR, or clear status: blocked) before opening the upstream PR.`,
    };
  }

  // Upstream owner/repo from upstream_issue URL.
  const upstream = parseUpstreamIssue(state.upstream_issue);
  if (!upstream) {
    return {
      ok: false,
      error: `cannot derive upstream owner/repo from current_state.upstream_issue (got "${state.upstream_issue ?? 'missing'}"). Expected form: https://github.com/<owner>/<repo>/issues/<n>.`,
    };
  }

  // Fork coordinates.
  const fork = state.fork;
  if (
    !fork ||
    !fork.owner?.trim() ||
    !fork.repo?.trim() ||
    !fork.branch?.trim()
  ) {
    return {
      ok: false,
      error:
        'current_state.fork must have owner, repo, and branch (the contributor fork the candidate fix lives on)',
    };
  }

  const upstreamRepo = `${upstream.owner}/${upstream.repo}`;
  const head = `${fork.owner}:${fork.branch}`;
  const body = appendAuthorshipFooter(args.pr_body ?? '');
  const dryRun = args.dry_run !== false; // default true

  // Build a paste-ready command string. spawn execution below uses an
  // argv array, not this string — they share the same arguments.
  // No `--label` here: upstream repos may not carry the label and
  // contributors usually can't create one. AI authorship is surfaced
  // via the body footer instead.
  const command = [
    'gh',
    'pr',
    'create',
    '--repo',
    upstreamRepo,
    '--head',
    head,
    '--draft',
    '--title',
    quoteShell(title),
    '--body',
    quoteShell(body),
  ].join(' ');

  if (dryRun) {
    return {
      ok: true,
      slug,
      upstream_repo: upstreamRepo,
      head,
      title,
      body,
      draft: true,
      dry_run: true,
      command,
    };
  }

  // dry_run=false → execute. Pre-flight checks first so a partial
  // failure doesn't leave the PR half-opened.

  // Guardrail 2: gh auth must be set up.
  const authCheck = ghRunner(['auth', 'status']);
  if (authCheck.status !== 0) {
    return {
      ok: false,
      error: `gh auth check failed: ${authCheck.stderr.trim() || '<no stderr>'}. Run 'gh auth login' first.`,
    };
  }

  // Fork must exist and be reachable by the active gh auth.
  const forkCheck = ghRunner([
    'repo',
    'view',
    `${fork.owner}/${fork.repo}`,
    '--json',
    'name',
  ]);
  if (forkCheck.status !== 0) {
    return {
      ok: false,
      error: `fork ${fork.owner}/${fork.repo} not found or inaccessible. Create it manually with 'gh repo fork ${upstreamRepo}' first — this tool does not fork on the caller's behalf.`,
    };
  }

  // The named branch must already be pushed to the fork.
  const branchCheck = ghRunner([
    'api',
    `repos/${fork.owner}/${fork.repo}/branches/${fork.branch}`,
  ]);
  if (branchCheck.status !== 0) {
    return {
      ok: false,
      error: `branch ${fork.branch} not found on fork ${fork.owner}/${fork.repo}. Push the fix branch to the fork before calling this tool.`,
    };
  }

  // Open the PR. --draft is hard-coded; caller cannot opt out.
  // No --label here (see the comment near the command builder above).
  const create = ghRunner([
    'pr',
    'create',
    '--repo',
    upstreamRepo,
    '--head',
    head,
    '--draft',
    '--title',
    title,
    '--body',
    body,
  ]);
  if (create.status !== 0) {
    return {
      ok: false,
      error: `gh pr create failed: ${create.stderr.trim() || '<no stderr>'}`,
    };
  }

  // gh pr create prints the PR URL to stdout on success.
  const prUrl = create.stdout.trim().split('\n').pop() ?? '';

  return {
    ok: true,
    slug,
    upstream_repo: upstreamRepo,
    head,
    title,
    body,
    draft: true,
    dry_run: false,
    command,
    pr_url: prUrl,
  };
}

export const CREATE_FORK_PR_TOOL = {
  name: 'create_fork_pr',
  description:
    "Open a draft PR on the upstream repository from the contributor's already-pushed fork branch. The output side of the round-trip loop. Conservative by design: `dry_run` defaults to true (returns the gh command without executing); `--draft` is mandatory (caller cannot opt out); AI authorship is disclosed via a boilerplate footer appended to the PR body (the `ai: generated` LABEL from AGENTS.md §4.6 is Vivarium-internal and is intentionally NOT applied — upstream repos rarely carry it and contributors usually lack permission to create it). The tool refuses to run unless `computeNextAction(current_state) === 'open_fork_pr'` — that single check enforces all the round-trip preconditions in one place (verdicts captured with the expected polarity, the Vivarium-side PR already opened, no existing upstream PR, status not blocked/merged). The fork branch must already exist on GitHub — this tool does NOT clone, commit, or push on the caller's behalf, and does NOT create the fork (use `gh repo fork` manually first). Pair with `verify_and_report_fix` upstream of this call and with `prepare_fix_candidate` (Layer 1) when registering a fix-candidate spec.",
  inputSchema: {
    type: 'object' as const,
    properties: {
      slug: {
        type: 'string' as const,
        pattern: '^[a-z0-9]+(-[a-z0-9]+)*$',
        description:
          "Kebab-case recipe slug (e.g. 'lark-1585', 'bash-local-shadows-exit'). Must exist in the catalogue.",
      },
      current_state: {
        type: 'object' as const,
        description:
          "Parsed roundtrip.json contents. Must contain `upstream_issue`, `fork` (owner/repo/branch), and `verdicts` with both `unfixed.verdict='reproduced'` and `fixed.verdict='unreproduced'`. The tool refuses to run otherwise.",
        additionalProperties: true,
      },
      pr_title: {
        type: 'string' as const,
        minLength: 1,
        description:
          "PR title. Caller is responsible for following the upstream project's commit / PR title conventions (Conventional Commits, etc.).",
      },
      pr_body: {
        type: 'string' as const,
        description:
          "PR body (Markdown). Defaults to empty. Include a link back to the Vivarium recipe and the upstream issue, and disclose AI authorship per AGENTS.md §4.6 (the `ai: generated` label is applied automatically; surfacing the disclosure in the body is good practice).",
      },
      dry_run: {
        type: 'boolean' as const,
        default: true,
        description:
          'When true (the default), the tool returns the exact `gh pr create` command + a structured summary WITHOUT calling gh. Set to false to actually open the PR. The MCP server never opens an upstream PR by accident.',
      },
    },
    required: ['slug', 'current_state', 'pr_title'],
  },
} as const;
