#!/usr/bin/env bun

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { FAVICONS, FOOTER_MESSAGE_HTML, GITHUB_REPO_URL } from './site-chrome';
import { SITE_BASE, SITE_ROOT } from './site-paths';

const LOCALES = ['en', 'ja'] as const;
type Locale = (typeof LOCALES)[number];

const OUT_PATH = join(
  SITE_ROOT,
  '..',
  '..',
  'src',
  'layer1_wasm',
  '_assets',
  'chrome-data.js',
);

interface NavEntry {
  text: string;
  link: string;
  activeMatch?: string;
}

interface ChromeNavItem {
  text: string;
  link: string;
}

const BASE = SITE_BASE.replace(/\/$/, '');

function absoluteLink(lang: Locale, link: string): string {
  const localePrefix = lang === 'en' ? BASE : `${BASE}/ja`;
  return `${localePrefix}${link}`;
}

function resolveNavLink(lang: Locale, link: string): string | null {
  const localeRoot = join(SITE_ROOT, lang);
  const rel = link.replace(/^\//, '');
  const candidates: string[] = [];
  if (rel === '' || rel.endsWith('/')) {
    const dir = rel.replace(/\/$/, '');
    candidates.push(join(localeRoot, dir, 'index.md'));
    candidates.push(join(localeRoot, dir, 'index.mdx'));
  } else {
    candidates.push(join(localeRoot, `${rel}.md`));
    candidates.push(join(localeRoot, `${rel}.mdx`));
    candidates.push(join(localeRoot, rel, 'index.md'));
    candidates.push(join(localeRoot, rel, 'index.mdx'));
  }
  for (const c of candidates) {
    if (existsSync(c)) return c;
  }
  return null;
}

function readNav(lang: Locale): NavEntry[] {
  const navPath = join(SITE_ROOT, lang, '_nav.json');
  if (!existsSync(navPath)) {
    console.error(`ERROR: ${navPath} not found.`);
    process.exit(1);
  }
  const parsed = JSON.parse(readFileSync(navPath, 'utf-8'));
  if (!Array.isArray(parsed)) {
    console.error(`ERROR: ${navPath} must contain a JSON array.`);
    process.exit(1);
  }
  return parsed as NavEntry[];
}

export function renderChromeData(
  navByLocale: Record<Locale, ChromeNavItem[]>,
): string {
  const lines: string[] = [
    '// AUTO-GENERATED by docs/scripts/generate-repro-chrome.ts.',
    '// Source of truth: docs/site/{en,ja}/_nav.json.',
    '// Do not edit by hand — run `mise run recipes:index` and commit.',
    '',
    'export const NAV_ITEMS = {',
  ];
  for (const lang of LOCALES) {
    lines.push(`  ${lang}: [`);
    for (const item of navByLocale[lang]) {
      lines.push(
        `    { text: ${JSON.stringify(item.text)}, link: ${JSON.stringify(item.link)} },`,
      );
    }
    lines.push('  ],');
  }
  lines.push('};');
  lines.push('');
  lines.push(`export const SITE_BASE = ${JSON.stringify(SITE_BASE)};`);
  lines.push('');
  lines.push(`export const GH_REPO = ${JSON.stringify(GITHUB_REPO_URL)};`);
  lines.push('');
  lines.push(
    `export const FOOTER_MESSAGE_HTML = ${JSON.stringify(FOOTER_MESSAGE_HTML)};`,
  );
  lines.push('');
  lines.push('export const FAVICONS = [');
  for (const icon of FAVICONS) {
    lines.push(`  ${JSON.stringify(icon)},`);
  }
  lines.push('];');
  lines.push('');
  return lines.join('\n');
}

export function buildNavByLocale(): Record<Locale, ChromeNavItem[]> {
  const out = {} as Record<Locale, ChromeNavItem[]>;
  const dead: string[] = [];
  for (const lang of LOCALES) {
    const entries = readNav(lang);
    out[lang] = entries.map((entry, i) => {
      if (resolveNavLink(lang, entry.link) === null) {
        dead.push(
          `docs/site/${lang}/_nav.json[${i}] ${JSON.stringify(entry.text)} -> ` +
            `${entry.link}: no matching page under docs/site/${lang}/`,
        );
      }
      return { text: entry.text, link: absoluteLink(lang, entry.link) };
    });
  }
  if (dead.length > 0) {
    console.error(
      'ERROR: nav entries point at pages that do not exist:\n  ' +
        `${dead.join('\n  ')}\n` +
        'Add the page, fix the link, or remove the entry.',
    );
    process.exit(1);
  }
  return out;
}

if (import.meta.main) {
  const nav = buildNavByLocale();
  const rendered = renderChromeData(nav);
  const previous = existsSync(OUT_PATH) ? readFileSync(OUT_PATH, 'utf-8') : '';
  if (previous !== rendered) {
    writeFileSync(OUT_PATH, rendered, 'utf-8');
    console.error(`Wrote ${OUT_PATH}`);
  } else {
    console.error(`${OUT_PATH} already up to date.`);
  }
}
