#!/usr/bin/env bun

import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { SITE_API_DIR, SITE_ROOT } from './site-paths';

interface ProjectEntry {
  project: string;
  display_name: string;
  tagline?: string;
  description?: string;
}

interface ProjectsIndex {
  index: 'v1';
  projects: ProjectEntry[];
}

const LOCALES = ['en', 'ja'] as const;

const MDX_HEADER_NOTE = [
  '{/* AUTO-GENERATED by docs/scripts/generate-project-pages.ts. */}',
  '{/* Regenerated whenever the set of projects changes (i.e. a new */}',
  '{/* project shows up in docs/site/public/api/projects.json). DO NOT EDIT */}',
  '{/* by hand — edit the docs/site/_data/projects.json overlay or */}',
  '{/* the ProjectPage component instead. */}',
].join('\n');

function buildMdx(lang: 'en' | 'ja', entry: ProjectEntry): string {
  const fallbackTitle =
    lang === 'ja'
      ? `${entry.display_name} の再現`
      : `${entry.display_name} reproductions`;
  return [
    '---',
    'pageType: doc',
    `title: ${JSON.stringify(fallbackTitle)}`,
    'sidebar: false',
    '---',
    '',
    MDX_HEADER_NOTE,
    '',
    "import { ProjectPage } from '../../../_components/ProjectPage';",
    '',
    `<ProjectPage lang=${JSON.stringify(lang)} project=${JSON.stringify(entry.project)} />`,
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const projectsPath = join(SITE_API_DIR, 'projects.json');

  const raw = await readFile(projectsPath, 'utf-8');
  const parsed = JSON.parse(raw) as ProjectsIndex;
  if (!Array.isArray(parsed.projects)) {
    console.error(
      `ERROR: ${projectsPath} did not contain a projects array; ` +
        'run `mise run recipes:index` to regenerate it first.',
    );
    process.exit(1);
  }

  let written = 0;
  for (const lang of LOCALES) {
    const baseDir = join(SITE_ROOT, lang, 'repro');
    for (const entry of parsed.projects) {
      const dir = join(baseDir, entry.project);
      try {
        const existing = await readFile(join(dir, 'index.mdx'), 'utf-8');
        if (existing.includes('AUTO-GENERATED')) {
          await rm(dir, { recursive: true, force: true });
        }
      } catch {}
    }

    for (const entry of parsed.projects) {
      const dir = join(baseDir, entry.project);
      await mkdir(dir, { recursive: true });
      const file = join(dir, 'index.mdx');
      await writeFile(file, buildMdx(lang, entry), 'utf-8');
      written += 1;
    }
  }

  console.error(
    `Wrote ${written} project landing page(s) ` +
      `(${parsed.projects.length} project(s) × ${LOCALES.length} locale(s)).`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
