import { createReadStream, existsSync, statSync } from 'node:fs';
import type { IncomingMessage, ServerResponse } from 'node:http';
import path from 'node:path';
import { REPO_ROOT, REPRO_BASE_PATH, SITE_BASE } from './site-paths';

const REPRO_ROOTS = [
  path.join(REPO_ROOT, 'src', 'layer1_wasm'),
  path.join(REPO_ROOT, 'src', 'layer2_docker'),
  path.join(REPO_ROOT, 'src', 'layer3_thirdway'),
];
const REPRO_URL_RE = new RegExp(
  `^${escapeRegExp(SITE_BASE.replace(/\/$/, ''))}(?:/(ja))?/repro/([^?#]*)(?:[?#].*)?$`,
);

const REPRO_MIME: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.mjs': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.wasm': 'application/wasm',
  '.ico': 'image/x-icon',
  '.map': 'application/json; charset=utf-8',
};

type Next = () => void;

interface MiddlewareHost {
  middlewares: {
    use(
      handler: (req: IncomingMessage, res: ServerResponse, next: Next) => void,
    ): void;
  };
}

export function resolveReproFile(
  rawSubpath: string,
  lang: 'en' | 'ja' = 'en',
): string | null {
  const subpath = rawSubpath || '';

  let trailingFile = '';
  let lookupPath = subpath;
  if (lookupPath === '' || lookupPath.endsWith('/')) {
    trailingFile = 'index.html';
    if (lookupPath.endsWith('/')) lookupPath = lookupPath.slice(0, -1);
  }

  const segments = lookupPath === '' ? [] : lookupPath.split('/');

  const candidates: string[] = [];
  if (segments.length === 0) {
  } else if (segments[0]?.startsWith('_')) {
    candidates.push(joinDisk(segments, trailingFile));
  } else if (segments.length === 1) {
  } else {
    const project = segments[0]!;
    const issuePath = segments[1]!;
    const rest = segments.slice(2);
    const prefixSlug = `${project}-${issuePath}`;
    candidates.push(joinDisk([prefixSlug, ...rest], trailingFile));
    const overrideSlug = issuePath;
    candidates.push(joinDisk([overrideSlug, ...rest], trailingFile));
  }

  for (const candidate of candidates) {
    for (const root of REPRO_ROOTS) {
      const abs = path.join(root, candidate);
      if (!existsSync(abs)) continue;
      const s = statSync(abs);
      if (s.isDirectory()) {
        const idx = path.join(abs, 'index.html');
        if (existsSync(idx)) return localise(idx, lang);
        continue;
      }
      return localise(abs, lang);
    }
  }
  return null;
}

function localise(filePath: string, lang: 'en' | 'ja'): string {
  if (lang !== 'ja' || !filePath.endsWith('index.html')) return filePath;
  const ja = filePath.replace(/index\.html$/, 'index.ja.html');
  if (existsSync(ja)) return ja;
  console.warn(
    `[vivarium] no index.ja.html next to ${filePath}; serving English. ` +
      'Run `mise run repro:i18n` after adding i18n.ja.json.',
  );
  return filePath;
}

function joinDisk(segments: string[], trailingFile: string): string {
  const base = segments.join('/');
  if (!trailingFile) return base;
  return base ? `${base}/${trailingFile}` : trailingFile;
}

export function setupReproDevMiddleware(
  server: MiddlewareHost | null | undefined,
): void {
  if (server == null) return;
  server.middlewares.use((req, res, next) => {
    const url = req.url ?? '';
    const match = url.match(REPRO_URL_RE);
    if (!match) return next();
    const lang = match[1] === 'ja' ? 'ja' : 'en';
    const subpath = match[2] ?? '';
    const filePath = resolveReproFile(subpath, lang);
    if (!filePath) {
      if (subpath === '' || subpath.endsWith('/')) {
        return next();
      }
      if (!path.extname(subpath)) {
        return next();
      }
      res.statusCode = 404;
      res.setHeader('Content-Type', 'text/plain; charset=utf-8');
      res.end(
        `404: ${subpath} not found in src/layer{1,2,3}_*/.\n` +
          'For Rust reproductions: run `cargo build --release --target wasm32-wasip1` in the recipe directory.\n' +
          'For Layer 2 verdict.json: the file is generated by CI; not present in local dev.\n',
      );
      return;
    }

    const ext = path.extname(filePath).toLowerCase();
    res.setHeader(
      'Content-Type',
      REPRO_MIME[ext] ?? 'application/octet-stream',
    );
    res.setHeader('Cache-Control', 'no-store');
    if (filePath.endsWith('sw.js')) {
      res.setHeader('Service-Worker-Allowed', `${REPRO_BASE_PATH}/`);
    }
    createReadStream(filePath).pipe(res);
  });
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
