name: Check Conventional Commit

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    uses: aletheia-works/.github/.github/workflows/commitlint.yml@2869d127c99b5cd8bcfb22d7ade8a31d1204019c # main
