name: Terraform State Backup

on:
  schedule:
    - cron: '0 3 * * 1'

  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed

  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  backup:
    if: |
      github.repository_owner == 'aletheia-works' &&
      (github.event_name != 'workflow_run' ||
       github.event.workflow_run.conclusion == 'success')
    uses: aletheia-works/.github/.github/workflows/terraform-state-backup.yml@1d569c881f73c1c9215fae92ad15e9d223a8d2c8 # main
    with:
      working_directory: infra/github
    secrets:
      TF_TOKEN_GITHUB: ${{ secrets.TF_TOKEN_GITHUB }}
