name: Terraform Plan

on:
  pull_request_target:
    paths:
      - 'infra/github/**'
      - '.github/workflows/terraform-plan.yml'

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  plan:
    if: github.repository_owner == 'aletheia-works'
    uses: aletheia-works/.github/.github/workflows/terraform-plan.yml@ffd7b8b9619fe8da13233a21c920b4d56b126f28 # main
    with:
      working_directory: infra/github
    secrets: inherit
