name: Tofu fmt autofix

on:
  pull_request_target:
    paths:
      - 'infra/github/**'
      - '.github/workflows/tofu-fmt-autofix.yml'

permissions:
  contents: write
  pull-requests: read

jobs:
  autofix:
    if: github.repository_owner == 'aletheia-works'
    uses: aletheia-works/.github/.github/workflows/terraform-autofix.yml@f8efae13d9ff4ea96692f7feac3cfdc4a7add308 # main
    with:
      working_directory: infra/github
      commit_message: 'style(infra): tofu fmt -recursive'
    secrets: inherit
